### ISSUE TITLE
问一下这是什么原因

### ISSUE THREAD

**Issue by jarl0415** [Kuingsmile/word-GPT-Plus#1]
![image](https://user-images.githubusercontent.com/41228756/235042187-5e172e47-ccab-404c-a9df-7a0e89a325cf.png)

**Comment by Kuingsmile** [comment]
用的是哪个manifest.xml,还是自己启动的服务

**Comment by jarl0415** [comment]
用的中国区那个，现在是这样 
![image](https://user-images.githubusercontent.com/41228756/235043747-f4868cd3-8a38-4360-a7c7-88963a9943a7.png)

**Comment by Kuingsmile** [comment]
![image](https://user-images.githubusercontent.com/96409857/235044269-e34dfe48-4dea-4ad8-ba5a-57e97525738d.png)
我自己这边是正常的
![image](https://user-images.githubusercontent.com/96409857/235044500-e47ef266-5d43-4c59-bc5c-9f66810fa8ea.png)
这里不太对，如果用中国区的manifest.xml的话，标题应该是GPT PLus， Word GPT Plus这个是需要本地搭服务的方式显示的标题
[manifest.zip](https://github.com/Kuingsmile/word-GPT-Plus/files/11349457/manifest.zip)

**Comment by jarl0415** [comment]
解决了，   我将共享文件夹那个设置成了everyone 出来了  感谢

**Comment by Kuingsmile** [comment]
> 解决了， 我将共享文件夹那个设置成了everyone 出来了 感谢

好的~

**Comment by Kuingsmile** [comment]
@jarl0415  国内服务器由于技术原因无法做到实时同步更新，已经remove掉了，请换用通用服务器的manifest.xml哈
