### ISSUE TITLE
[Bug]: Error: Network Error

### ISSUE THREAD

**Issue by 2731382028** [Kuingsmile/word-GPT-Plus#10]
### 前置阅读 | Pre-reading

- [x] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [x] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2019 retail

### Error: Network Error，所有都设置ok，用的openal aip，服务是用的官方提供的

**图片如下，不知道怎么处理，谢谢大佬了**
![WC}I{@UY3H_3E%Q9MG1{F14](https://github.com/Kuingsmile/word-GPT-Plus/assets/134201346/e1fc240a-4130-41ec-a1cf-0b4625db43ba)
![)(L%}42$A@OG )V$CXF)BW8](https://github.com/Kuingsmile/word-GPT-Plus/assets/134201346/8c5323cb-1091-43e8-8e78-77e363442f72)

**Comment by 2731382028** [comment]
![612ON}())T{O76LCNBW 9C](https://github.com/Kuingsmile/word-GPT-Plus/assets/134201346/2c32a0e5-03c9-46b1-88a0-aa1bdf1a1d30)

**Comment by Kuingsmile** [comment]
用官方api地址的时候不用填转发域名
