### ISSUE TITLE
[Bug]: Error: Request failed with status code 429

### ISSUE THREAD

**Issue by Haruto5627** [Kuingsmile/word-GPT-Plus#14]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 问题重现 | Bug reproduce

首先感谢你推出的gpt plus插件，它在我改论文的时候，帮了非常大的忙！
但是我今天打开时，遇到了一个问题，Error: Request failed with status code 429。不太懂是什么意思。
下面是我的设置截图
![1](https://github.com/Kuingsmile/word-GPT-Plus/assets/135297460/380eea6d-26eb-4419-a7d8-b948125da4d9)

**Comment by Kuingsmile** [comment]
一般来说是ip对应的请求速率到上限了，可能和你的梯子或网络相关

**Comment by Haruto5627** [comment]
你好！根据你的回答，我尝试更换了网络，和梯子的节点，目前依旧是Request failed with status code 429。word gpt网页是可以正常打开的，但无法好像回答问题。

**Comment by Haruto5627** [comment]
我明白了，是我自己的API Free trial usage到期了
![2](https://github.com/Kuingsmile/word-GPT-Plus/assets/135297460/a10aa5dc-61a4-4415-b222-c7b2a2ae593f)
