### ISSUE TITLE
问题：没找到填写api key或者access token的地方

### ISSUE THREAD

**Issue by linkwoodworking** [Kuingsmile/word-GPT-Plus#19]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

读了两遍readme，插件装上了，但是没找到填写api key或者access token的地方，请指教，谢谢

**Comment by linkwoodworking** [comment]
在closed里找到了。。。麻烦可以加在readme里，能省时间，谢谢

**Comment by Kuingsmile** [comment]
> 在closed里找到了。。。麻烦可以加在readme里，能省时间，谢谢

ok 我改下readme
