### ISSUE TITLE
添加API

### ISSUE THREAD

**Issue by FITZET** [Kuingsmile/word-GPT-Plus#2]
请问怎么添加自己的API呀，点start一直让我Set API Key

**Comment by Kuingsmile** [comment]
之前的代码有bug，刚才已经修复了哈，重启word再试一下看看

**Comment by Kuingsmile** [comment]
如果是自己启动的服务，需要git pull一下最新的代码

**Comment by FITZET** [comment]
> 如果是自己启动的服务，需要git pull一下最新的代码

我用的是你们提供的，没有自己部署，请问这种情况下在哪里填API号呀

**Comment by Kuingsmile** [comment]
> > 如果是自己启动的服务，需要git pull一下最新的代码
> 
> 我用的是你们提供的，没有自己部署，请问这种情况下在哪里填API号呀

点击setting或者设置进去填写自己的API key或access token
![image](https://user-images.githubusercontent.com/96409857/235435501-56571996-d68a-42f6-ad5b-95d3e7570286.png)
