### ISSUE TITLE
[Bug]: Unable to load plugin

### ISSUE THREAD

**Issue by JOKER120YL** [Kuingsmile/word-GPT-Plus#20]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

1.人在海外，word.msq.pub可登录
2.按照流程设置成功
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/50386965/0f312ae7-6acf-44d0-9bb2-a72a86225218)
已设置共享
3.一直加载错误或无网络连接
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/50386965/79c3a137-5297-47be-877b-b893712b0cac)
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/50386965/94197e38-06e1-45ec-b6c5-be61abd169fa)

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/8629629e-3cd8-4f0e-889f-d60ede063b87)

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/1119753e-15e3-4dc3-afc5-f4d20e121dfc)

点这个三角按钮，弹出菜单里选attach debugger，看下控制台有报什么错，还有network里有什么错误

我自己电脑上是可以正常加载的

**Comment by JOKER120YL** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/50386965/fc73d7ff-3168-4f11-9c3b-2ee2e27f904b)
调试器打开后就会自动闪退

**Comment by JOKER120YL** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/50386965/f1ec3a9a-537e-41d1-a306-b976df1b9456)

**Comment by LPLlpl1** [comment]
我也是调试器打开总是闪退，加载项错误，怎么解决
