### ISSUE TITLE
[Feature]: 希望添加自定义域名

### ISSUE THREAD

**Issue by Sir-H** [Kuingsmile/word-GPT-Plus#21]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

1.希望添加chatgpt自定义域名

**Comment by Sir-H** [comment]
第三方api域名以及自定义请求路劲

**Comment by Kuingsmile** [comment]
api转发？

**Comment by Sir-H** [comment]
就类似这样的调用网址   http://xx.xx.xx/v1/chat/completions

**Comment by Kuingsmile** [comment]
> 就类似这样的调用网址 http://xx.xx.xx/v1/chat/completions

好 我看下~

**Comment by Sir-H** [comment]
好的 谢谢

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/619748b4-8708-4260-b7f2-3dc8ff45a37f)
转发域名 应该就是你需要的自定义域名 我是配合https://github.com/beidongjiedeguang/openai-forward用的

**Comment by urafrik** [comment]
转发key会报错
401 Incorrect API key provided: sk-bez9T***************************************fT9g. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by Kuingsmile** [comment]
你的key有问题

**Comment by urafrik** [comment]
转发key会报错，用的这个项目的转发https://github.com/chatanywhere/GPT_API_free

401 Incorrect API key provided: sk-bez9T***************************************fT9g. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by msxfXF** [comment]
我在本地运行一个大模型，并暴露了类似 openAI 的接口。但填入转发域名后，一直提示 API 密钥错误？请问可以跳过验证吗？

**Comment by msxfXF** [comment]
word 插件，用的是您已经部署好的，其中也没找到 web-api 选项。用的是 official + 转发域名。
希望可以指导一下。

**Comment by xiaoToby** [comment]
> word 插件，用的是您已经部署好的，其中也没找到 web-api 选项。用的是 official + 转发域名。
> 希望可以指导一下。



> 我在本地运行一个大模型，并暴露了类似 openAI 的接口。但填入转发域名后，一直提示 API 密钥错误？请问可以跳过验证吗？



> 我在本地运行一个大模型，并暴露了类似 openAI 的接口。但填入转发域名后，一直提示 API 密钥错误？请问可以跳过验证吗？

解决了嘛@msxfXF
