### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by davechenxy** [Kuingsmile/word-GPT-Plus#22]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

这个对mac的word也有效吗？ 我发现我无法加载这个插件

**Comment by Kuingsmile** [comment]
没有在mac上测试过 按这个 https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac 试试
