### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tianci-chai** [Kuingsmile/word-GPT-Plus#24]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2019 retail

### 问题重现 | Bug reproduce

使用自定义域名显示incorrect API key，API及域名来自于https://github.com/chatanywhere/GPT_API_free

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> 
> - [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> - [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)
> 
> ### 服务类型 | Service Type
> 
> Official hosted service
> 
> ### 系统信息 | System Information
> 
> Windows
> 
> ### Office 版本 | Office Version
> 
> office 2019 retail
> 
> ### 问题重现 | Bug reproduce
> 
> 使用自定义域名显示incorrect API key，API及域名来自于https://github.com/chatanywhere/GPT_API_free

可复现 正在排查

**Comment by Kuingsmile** [comment]
经查看该项目的免费API key限制较多且不透明难以拍错，将不予跟进，请尽量使用官方接口或azure openai
