### ISSUE TITLE
[Feature]: 账号中生成的new chat感觉可以增加一个批量删除的功能

### ISSUE THREAD

**Issue by ykanccs** [Kuingsmile/word-GPT-Plus#25]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

我是使用[access token]进行连接在每次使用时每一句话都会在gpt账户里生成一个new chat（这个记录感觉也还是有必要留存），但是会影响一定的日常其他方面的使用，感觉可以给每一个新生成的对话框加上特定的前缀，然后增加一个批量删除功能

**Comment by Kuingsmile** [comment]
access token连接是走的网页版破解api，目前没有删除对话的接口哈
