### ISSUE TITLE
[Bug]: 当前没有加载项可用

### ISSUE THREAD

**Issue by zhengnan365** [Kuingsmile/word-GPT-Plus#27]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

按照步骤操作，采用Service hosted by you，但一直显示当前没有加载项可用，不知道为什么？

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/word-GPT-Plus/blob/master/release/instant-use/manifest.xml  是用的这个么

**Comment by zhengnan365** [comment]
下载这个可以了。我用的readme  中那个链接下载的，可能不是最新的。谢谢你
