### ISSUE TITLE
[Bug]: 使用access token时报错：TypeError: Load failed。用OpenAI的API就可以，为啥？

### ISSUE THREAD

**Issue by kaedeharakazuhaaz** [Kuingsmile/word-GPT-Plus#30]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac(arm64)

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

可以用OpenAI的API，但是用access token就报错：TypeError: Load failed。我在其他用access token的软件上试了一下，我的token是可以用的，这是为什么？

**Comment by Kuingsmile** [comment]
access token需要使用api反代服务，目前在使用的反代地址已失效，看了下能用的反代服务有密钥泄露和封号风险，因此已经更新将access token使用方式移除
