### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by urafrik** [Kuingsmile/word-GPT-Plus#34]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

转发key会报错，用的这个项目的转发https://github.com/chatanywhere/GPT_API_free

401 Incorrect API key provided: sk-bez9T***************************************fT9g. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by Kuingsmile** [comment]
你的key有问题 另外本项目不对此类免费GPT API项目提供任何支持

**Comment by urafrik** [comment]
key应该是没问题的，在其他项目也是能用的
