### ISSUE TITLE
[Bug]: cf已构建，并且可以正常打开。但是word内的插件显示找不到页面

### ISSUE THREAD

**Issue by mizb** [Kuingsmile/word-GPT-Plus#35]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/22237339/f35ebb05-5855-457e-8fd5-59739b9ab69f)

**Comment by Kuingsmile** [comment]
自己cf构建的话 修改manifest.xml里的地址了没

**Comment by mizb** [comment]
修改过了，应该cf那能正常打开，页面也能显示。
