### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by artrusx** [Kuingsmile/word-GPT-Plus#36]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

All

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

The ForwardDomain parameter is not applied because of an error in this line. The correct name of the parameter is "baseURL". 
const config = { apiKey, baseURL: basePath, dangerouslyAllowBrowser: true }

**Comment by Kuingsmile** [comment]
Thanks，this has been fixed.
