### ISSUE TITLE
[Feature]: endpoint setting for gemini

### ISSUE THREAD

**Issue by johnd0e** [Kuingsmile/word-GPT-Plus#37]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

There is `endpoint` setting for "palm" API.
It would be great to have same settings for "Gemini Pro".

**Comment by Kuingsmile** [comment]
looks good

**Comment by johnd0e** [comment]
BTW there is alternative lib - https://github.com/EvanZhouDev/gemini-ai

**Comment by johnd0e** [comment]
> setting the base_url is not supported right now.

There is an option now: https://github.com/google/generative-ai-js/pull/73
