### ISSUE TITLE
[Bug]: TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Legendary-creator** [Kuingsmile/word-GPT-Plus#39]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

<img width="252" alt="Snipaste_2024-01-18_11-29-42" src="https://github.com/Kuingsmile/word-GPT-Plus/assets/111637942/3cec6917-47a2-4f77-a1a0-500cf4be681e">

Key正常,采用instant-use,之前运行没有问题,就这几天出现上述情况,在其他IP不同电脑按照教程搭建依然存在问题,请作者支招,感谢

**Comment by Kuingsmile** [comment]
退出word，然后重新进入再试试，前两天修复转发域名bug的修复方式有点问题，刚刚又改了下

**Comment by Legendary-creator** [comment]
问题得到解决,感谢帮助
