### ISSUE TITLE
[Bug]: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by HiXiaolin** [Kuingsmile/word-GPT-Plus#4]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 问题重现 | Bug reproduce

TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
 yarn build 部署以后，打开页面会报这个错误， 我的nginx服务也已经配置好了，不知道问题出在哪了

**Comment by Kuingsmile** [comment]
> 网络正常且按步骤安装插件，但提示无网络

安装的是哪个版本，自己搭建的服务还是用的word.msq.pub这个服务

**Comment by LW030406** [comment]
使用的gptplus自带的内容，没有自己搭建



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 9:25 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





  
网络正常且按步骤安装插件，但提示无网络
  
安装的是哪个版本，自己搭建的服务还是用的word.msq.pub这个服务

**Comment by LW030406** [comment]
就是插件可以被word识别到，并且挂载，但是点击插件的时候就告诉我无法启动，或者没网



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 9:25 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





  
网络正常且按步骤安装插件，但提示无网络
  
安装的是哪个版本，自己搭建的服务还是用的word.msq.pub这个服务

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/c32c4614-88aa-41c8-8af8-44d372cfc4b5)
这里 Word GPT Plus是自建， GPT Plus是使用我的网站服务，确认下是哪个

**Comment by LW030406** [comment]
网页可以打开，但是word里面打不开，提示无网络，电脑正常联网，有tz和api



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 10:51 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 

 这里 Word GPT Plus是自建， GPT Plus是使用我的网站服务，确认下是哪个

**Comment by LW030406** [comment]
wordgptplus在我电脑上的word无法启动



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 10:51 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 

 这里 Word GPT Plus是自建， GPT Plus是使用我的网站服务，确认下是哪个

**Comment by Kuingsmile** [comment]
> wordgptplus在我电脑上的word无法启动 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Kuingsmile ***@***.***&gt; Date: Fri,Jul 7,2023 10:51 AM To: Kuingsmile/word-GPT-Plus ***@***.***&gt; Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4) 这里 Word GPT Plus是自建， GPT Plus是使用我的网站服务，确认下是哪个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

https://github.com/Kuingsmile/word-GPT-Plus/blob/master/release/other/manifest.xml
要用这个文件来加载，你加载的应该是需要自己搭建的那一版

**Comment by LW030406** [comment]
当我点击下载链接弹出来的是xml内容页面，没有直接下载文件



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 10:55 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





  
wordgptplus在我电脑上的word无法启动 发自我的iPhone
 …
 ------------------ Original ------------------ From: Kuingsmile @.&gt; Date: Fri,Jul 7,2023 10:51 AM To: Kuingsmile/word-GPT-Plus @.&gt; Cc: LW030406 @.&gt;, Comment @.&gt; Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4) 这里 Word GPT Plus是自建， GPT Plus是使用我的网站服务，确认下是哪个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
https://github.com/Kuingsmile/word-GPT-Plus/blob/master/release/other/manifest.xml
 要用这个文件来加载，你加载的应该是需要自己搭建的那一版

**Comment by Kuingsmile** [comment]
https://raw.githubusercontent.com/Kuingsmile/word-GPT-Plus/master/release/other/manifest.xml

用下载软件或者电脑浏览器打开之后右键另存为

**Comment by LW030406** [comment]
好的，我回去看看



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 11:19 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 
https://raw.githubusercontent.com/Kuingsmile/word-GPT-Plus/master/release/other/manifest.xml
 
用下载软件或者电脑浏览器打开之后右键另存为

**Comment by LW030406** [comment]
仍然提示无网络



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 11:19 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 
https://raw.githubusercontent.com/Kuingsmile/word-GPT-Plus/master/release/other/manifest.xml
 
用下载软件或者电脑浏览器打开之后右键另存为

**Comment by LW030406** [comment]
用官方api需要使用科学上网吗



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 11:19 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 
https://raw.githubusercontent.com/Kuingsmile/word-GPT-Plus/master/release/other/manifest.xml
 
用下载软件或者电脑浏览器打开之后右键另存为

**Comment by LW030406** [comment]
为什么他不能根据我发的文本做出分析



发自我的iPhone


------------------ Original ------------------
From: Kuingsmile ***@***.***&gt;
Date: Fri,Jul 7,2023 11:19 AM
To: Kuingsmile/word-GPT-Plus ***@***.***&gt;
Cc: LW030406 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Kuingsmile/word-GPT-Plus] [Bug]: TypeError: Failed to execute'compile' on 'WebAssembly': Incorrect response MIME type. Expected'application/wasm'. (Issue #4)





 
https://raw.githubusercontent.com/Kuingsmile/word-GPT-Plus/master/release/other/manifest.xml
 
用下载软件或者电脑浏览器打开之后右键另存为
