### ISSUE TITLE
[Feature]: 将项目打包成docker，可以在群晖中自建服务。

### ISSUE THREAD

**Issue by CaoKang-David** [Kuingsmile/word-GPT-Plus#40]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Linux

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

希望作者能将此项目打包成docker或者提供一个包管理为npm的分支，以方便在群晖的webstation或者容器里面部署

**Comment by Kuingsmile** [comment]
我试下

**Comment by CaoKang-David** [comment]
谢谢！

**Comment by Kuingsmile** [comment]
https://hub.docker.com/r/kuingsmile/word-gpt-plus

参考README对应内容运行docker和修改manifest文件

**Comment by CaoKang-David** [comment]
实在太感谢了！
