### ISSUE TITLE
[Feature]: 请问能否增加一个仅grammar check 的功能

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#41]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac(arm64)

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

请问能否增加一个仅grammar check 的功能
有时候稿件写差不多了，只需要检查下语法
另外，默认的几个prompt在哪里能看到呢
谢谢

**Comment by Kuingsmile** [comment]
grammar check我试下，另外内置prompt查看下面这个文件的`buildInPrompt`变量

https://github.com/Kuingsmile/word-GPT-Plus/blob/master/src/utils/constant.ts

**Comment by fredericky123** [comment]
感谢感谢！

**Comment by fredericky123** [comment]
另外一个小建议，默认的这些prompt在如果能在settings设置哪些显示哪些不显示 就更好了 
比如我不常用translation，自己可以直接取消显示了，节约空间（当然了这个功能非必须）
<img width="350" alt="image" src="https://github.com/Kuingsmile/word-GPT-Plus/assets/13982749/22ef7f5f-0cf7-4553-8e6d-bf3c2864dbdd">

**Comment by fredericky123** [comment]
这个academic的prompt应该还可以完善，会出现一些解释词，prompt可以多写一句话以达到删去的目的
另外，我还想替换SCI为SSCI或者某些期刊名，不知道能否可行
<img width="315" alt="image" src="https://github.com/Kuingsmile/word-GPT-Plus/assets/13982749/ef481c44-f970-4cfb-a5a5-c223b8d0c673">

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/b16f4454-4554-4876-9129-e3913c4c4bdb)
可以试下自己添加prompt

**Comment by fredericky123** [comment]
这两天更新了模型
请求支持呀
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by Kuingsmile** [comment]
> 这两天更新了模型 请求支持呀 https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

可以 我有空更新下 年底工作太忙了 o(╯□╰)o

**Comment by fredericky123** [comment]
> > 这两天更新了模型 请求支持呀 https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
> 
> 可以 我有空更新下 年底工作太忙了 o(╯□╰)o

辛苦啦

**Comment by Kuingsmile** [comment]
> > > 这两天更新了模型 请求支持呀 https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
> > 
> > 
> > 可以 我有空更新下 年底工作太忙了 o(╯□╰)o
> 
> 辛苦啦

添加了新的gpt-4模型
