### ISSUE TITLE
[Feature]: 访问速度没有官网的响应快，能否实现直接通过官网调用api呢

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#42]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac(arm64)

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

不太懂部署在pages 上的原理，发现访问速度没有访问openai官网的响应快，能否实现直接通过官网调用api实现work plus的功能呢

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)
> 
> ### 服务类型 | Service Type
> Official hosted service
> 
> ### 系统信息 | System Information
> Mac(arm64)
> 
> ### Office 版本 | Office Version
> microsoft 365
> 
> ### 功能请求 | Feature request
> 不太懂部署在pages 上的原理，发现访问速度没有访问openai官网的响应快，能否实现直接通过官网调用api实现work plus的功能呢

原理不一样，pages部署走的cf的cdn网络，如果你是国内访问网站会慢一点。有条件可以自己部署。

**Comment by fredericky123** [comment]
就是必须得通过pages部署一下服务是吧，（我看有些浏览器翻译插件是直接访问官网），我这里访问官网更快些，想着是不是可能直接访问openai官网实现功能

**Comment by Kuingsmile** [comment]
> 就是必须得通过pages部署一下服务是吧，（我看有些浏览器翻译插件是直接访问官网），我这里访问官网更快些，想着是不是可能直接访问openai官网实现功能

翻译插件可以 但是word里的插件还需要加载office.js包来操作文档

**Comment by fredericky123** [comment]
明白了 那就是还依赖个自己的服务器 靠只访问官网是实现不了了 谢谢啦

**Comment by Kuingsmile** [comment]
> 我在想既然可以优选cdn的ip加快访问速度，是不是可以利用这个项目进行优选ip https://github.com/XIU2/CloudflareSpeedTest 不过优选出来的ip替换manifest.xml里的哪个地方能实现加速访问呢

不如开个翻墙来的快 另外我记得优选ip应该是修改hosts用的

**Comment by fredericky123** [comment]
意思是把https://word.msq.pub/加入走代理的规则嘛 
我试试
