### ISSUE TITLE
[Feature]: 请求添加支持linux-arm64的DOCKER镜像

### ISSUE THREAD

**Issue by pzcn** [Kuingsmile/word-GPT-Plus#43]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

others

### 功能请求 | Feature request

请求添加支持linux-arm64的DOCKER镜像，谢谢
在action中，添加platforms参数即可，例如
`    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64`

**Comment by Kuingsmile** [comment]
可以 我改下

**Comment by Kuingsmile** [comment]
added
