### ISSUE TITLE
[Bug]: 关于使用自定义API_Base出现的问题

### ISSUE THREAD

**Issue by Rlxzmdd** [Kuingsmile/word-GPT-Plus#44]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

我使用的API由项目 https://github.com/aaamoon/copilot-gpt4-service 转换而来。
API 开头为 ghu_xxxx
API_BASE 尝试过 https://url.com 以及 https://url.com/v1/chat/completions 的形式。
目前一直显示 405 Method Not Allowed
请问是api格式的问题么？还是我api_base设置的问题；
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/13695917/aa55dc2e-6814-491d-bddd-2ebb43ea156a)

**Comment by Kuingsmile** [comment]
试下https://url.com/v1

**Comment by Rlxzmdd** [comment]
> 试下https://url.com/v1

已解决
