### ISSUE TITLE
[Bug]: Summary polishing and custom API buttons are not available

### ISSUE THREAD

**Issue by Legendary-creator** [Kuingsmile/word-GPT-Plus#46]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

![Picture1](https://github.com/Kuingsmile/word-GPT-Plus/assets/111637942/426f775f-1618-4a48-a21e-f545e13f2130)
Could you please recheck features and now only translation button work? thanks a lot for your help

**Comment by Kuingsmile** [comment]
I can't reproduce the problem, can you supply more infomations?

**Comment by Legendary-creator** [comment]
Now it works, I have no idea.
