### ISSUE TITLE
[Feature]: 这里有一个成熟的grammar check的功能，不知能否借鉴一下

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#47]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac(arm64)

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

https://www.loom.com/embed/21d7989d31614d7db00fc2feac0c4f3a
添加一个grammar & spelling check的功能，非常需要

**Comment by fredericky123** [comment]
这样的prompt还是达不到想要的效果，请求根据连接里的如何修改完善一下
I want you to act as a professional spelling and grammar corrector. Please do not elaborate. Please begin by editing the following text: ${text}

另外，academic prompt有拼写错误
<img width="938" alt="image" src="https://github.com/Kuingsmile/word-GPT-Plus/assets/13982749/31c3357d-8734-436c-a74e-3245e71750a7">

**Comment by Kuingsmile** [comment]
最新提交添加了grammar check的功能进行试运行

**Comment by fredericky123** [comment]
我来测试下效果，感谢！

**Comment by fredericky123** [comment]
目前使用起来效果非常不错，就是每次改了哪里需要自己比对，是不是grammar的功能是不要修改后的文字，而是要简洁性地直接给出建议毕竟好，又或者能以单个单词的形式对原文进行审阅式修订吗
