### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by csq-csq123** [Kuingsmile/word-GPT-Plus#48]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

出现错误403 true，我用的转发，转发api和key在其他里都是正常能用，如何解决？
![微信图片_20240310162138](https://github.com/Kuingsmile/word-GPT-Plus/assets/125939294/0edb5273-db02-4462-9791-1ff3c42f4be0)

**Comment by Kuingsmile** [comment]
1. 具体是什么转发服务，key的来源是否是官方
2. 需要具体报错信息，打开附加调试器在控制台查看

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/ea394068-2877-4477-94a4-426ad7628d1a)

**Comment by CelanXu** [comment]
> 1. 具体是什么转发服务，key的来源是否是官方
> 2. 需要具体报错信息，打开附加调试器在控制台查看
> 
> ![image](https://private-user-images.githubusercontent.com/96409857/311507454-ea394068-2877-4477-94a4-426ad7628d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODk3ODQsIm5iZiI6MTcxMDM4OTQ4NCwicGF0aCI6Ii85NjQwOTg1Ny8zMTE1MDc0NTQtZWEzOTQwNjgtMjg3Ny00NDc3LTk0YTQtNDI2YWQ3NjI4ZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNWU1NGJlMmEwZjgzNzkwNjc1YmRkNmY5NTMxNDViN2NhNzMxYzFlZmYzMWZhY2UyOGJiYTg4NTI0ZTgyNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lYqb_UeGyqleuCdCEBawZ3GcNqlluKciggmj9KH0sAc)

您好！我遇到的是相同的问题，用的是这家的转发API（https://zwxvec6g91g.feishu.cn/docx/KS7AddreTouQg6xs44Oc0ZgHnOg），提示401 Incorrect API key provided: sk-g8ljW***************************************SwxI. You can find your API key at https://platform.openai.com/account/api-keys.
控制台提示如下
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/84708952/a1ec059f-a4cf-4046-b196-f8d2c446df6d)

**Comment by iplane787** [comment]
需要把/v1加上，比如我用的https://api.aikey.one，那么要填https://api.aikey.one/v1
