### ISSUE TITLE
[Feature]: anyllm integration?

### ISSUE THREAD

**Issue by arm2arm** [Kuingsmile/word-GPT-Plus#49]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 功能请求 | Feature request

Any plans to enable ability to talk ti anyllm or ollama hosted models??
thanks

**Comment by Kuingsmile** [comment]
look good, will try

**Comment by Kuingsmile** [comment]
@arm2arm will add support for ollama in next version

**Comment by jaycecd** [comment]
请问ollama的模型可以通过自定义输入模型名称来调用吗？目前的ollama模型都是通过下拉框选择：
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/33342388/a650684d-9145-44d7-a52b-c36d20c70962)

但是开源社区发展的太快了，如果是每次出来一个新的LLM模型，单纯靠您手动添加感觉是不是有点不太高效？如果是做成prompt那样可以自定义添加的下拉框：

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/33342388/c28f6e45-3c05-4806-bd37-5a1c0d1dff19)

或者就单纯的一个文本框感觉就非常方便了~~

**Comment by jaycecd** [comment]
还有个小问题，烦请解答~~

我看releases里面说[v0.4.4](https://github.com/Kuingsmile/word-GPT-Plus/releases/tag/v0.4.4)已经支持llama3了

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/33342388/adb7e865-2c79-4754-9e9d-96514d2b1fa6)


但是为什么我本地的插件没有看到llama3的选项呢？

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/33342388/82204e6e-aa9d-4ef3-a510-0b51364e0951)


请问是我的GPT PLUS没有更新吗？如果是没有更新的话，该在哪里查看插件的版本，以及如何更新插件呢？

**Comment by Kuingsmile** [comment]
> 请问ollama的模型可以通过自定义输入模型名称来调用吗？目前的ollama模型都是通过下拉框选择： ![image](https://private-user-images.githubusercontent.com/33342388/333266285-a650684d-9145-44d7-a52b-c36d20c70962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjYyODUtYTY1MDY4NGQtOTE0NS00NGQ3LWE1MmItYzM2ZDIwYzcwOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMjhhZjMxYzkyNWFjNzI2NTMzOGVmMDJjNjYzZmFmYzBkNTRiNDkzYmU0NjE2NDVkMWU3MTBiNTVmMmFiOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sxfai9YMVLTY9I_d9mq-s06R4Jgnw3AFjZxN-gFidTE)
> 
> 但是开源社区发展的太快了，如果是每次出来一个新的LLM模型，单纯靠您手动添加感觉是不是有点不太高效？如果是做成prompt那样可以自定义添加的下拉框：
> 
> ![image](https://private-user-images.githubusercontent.com/33342388/333266711-c28f6e45-3c05-4806-bd37-5a1c0d1dff19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjY3MTEtYzI4ZjZlNDUtM2MwNS00ODA2LWJkMzctNWExYzBkMWRmZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzUxOTFiYzZhOGY0MzRjNDAwNTM3NzAzNTYzOTY0YjQwNjY2YzI5YmZiYmEyMGI4MDQ2NWU2ZjhmNzQ3ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CxVL_p4w2pNpYvXIMaXZYhqfo_J0h_m60oeQJchK4pU)
> 
> 或者就单纯的一个文本框感觉就非常方便了~~

这里后续加个输入框

**Comment by Kuingsmile** [comment]
> 还有个小问题，烦请解答~~
> 
> 我看releases里面说[v0.4.4](https://github.com/Kuingsmile/word-GPT-Plus/releases/tag/v0.4.4)已经支持llama3了
> 
> ![image](https://private-user-images.githubusercontent.com/33342388/333269465-adb7e865-2c79-4754-9e9d-96514d2b1fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjk0NjUtYWRiN2U4NjUtMmM3OS00NzU0LTllOWQtOTY1MTRkMmIxZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjNiYWEwZjBmNzAyODRkN2Q4OTBlNGY4YmE0YzE2OTQ3MzUzMzgyODBjNmMyZDJiYmM5MjUwYjZhZTJkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwE1GX94vOnsdSjd1FUkyuOhrjpqFBOamMz8GbNAPXQ)
> 
> 但是为什么我本地的插件没有看到llama3的选项呢？
> 
> ![image](https://private-user-images.githubusercontent.com/33342388/333269330-82204e6e-aa9d-4ef3-a510-0b51364e0951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjkzMzAtODIyMDRlNmUtYWE5ZC00ZWYzLWE1MTAtMGI1MTM2NGUwOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDUyMWE3NGE1NjQwYmMzNDljY2ViMjNjN2I5MDI3ZTgwYjkyNmI4ZDI2ZjAzMDA1M2IxNWE1NmJjMDhhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7qIpdtLUiEtYYS87yBj-AUcJuESlMwxWd4uznqLx4U)
> 
> 请问是我的GPT PLUS没有更新吗？如果是没有更新的话，该在哪里查看插件的版本，以及如何更新插件呢？

如果你是如下使用的
```
git clone https://github.com/Kuingsmile/Word-GPT-Plus.git
yarn
yarn run serve
```

那git拉取下最新代码 然后重新运行后续yarn和yarn run serve命令就可以，后续考虑底部添加个版本号方便识别

**Comment by jaycecd** [comment]
> > 还有个小问题，烦请解答~~
> > 我看releases里面说[v0.4.4](https://github.com/Kuingsmile/word-GPT-Plus/releases/tag/v0.4.4)已经支持llama3了
> > ![image](https://private-user-images.githubusercontent.com/33342388/333269465-adb7e865-2c79-4754-9e9d-96514d2b1fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjk0NjUtYWRiN2U4NjUtMmM3OS00NzU0LTllOWQtOTY1MTRkMmIxZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjNiYWEwZjBmNzAyODRkN2Q4OTBlNGY4YmE0YzE2OTQ3MzUzMzgyODBjNmMyZDJiYmM5MjUwYjZhZTJkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwE1GX94vOnsdSjd1FUkyuOhrjpqFBOamMz8GbNAPXQ)
> > 但是为什么我本地的插件没有看到llama3的选项呢？
> > ![image](https://private-user-images.githubusercontent.com/33342388/333269330-82204e6e-aa9d-4ef3-a510-0b51364e0951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjkzMzAtODIyMDRlNmUtYWE5ZC00ZWYzLWE1MTAtMGI1MTM2NGUwOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDUyMWE3NGE1NjQwYmMzNDljY2ViMjNjN2I5MDI3ZTgwYjkyNmI4ZDI2ZjAzMDA1M2IxNWE1NmJjMDhhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7qIpdtLUiEtYYS87yBj-AUcJuESlMwxWd4uznqLx4U)
> > 请问是我的GPT PLUS没有更新吗？如果是没有更新的话，该在哪里查看插件的版本，以及如何更新插件呢？
> 
> 如果你是如下使用的
> 
> ```
> git clone https://github.com/Kuingsmile/Word-GPT-Plus.git
> yarn
> yarn run serve
> ```
> 
> 那git拉取下最新代码 然后重新运行后续yarn和yarn run serve命令就可以，后续考虑底部添加个版本号方便识别

您好，我不是自己构建的服务，而是使用您这边使用Cloudflare Pages搭建的服务。看readme文件上面的描述，应该是自动更新的，但现在确实没有llama3，是不是您的releases和您搭建的服务没有匹配上（即releases更新了llama3，但是Cloudflare Pages没有更新）？

**Comment by Kuingsmile** [comment]
> > > 还有个小问题，烦请解答~~
> > > 我看releases里面说[v0.4.4](https://github.com/Kuingsmile/word-GPT-Plus/releases/tag/v0.4.4)已经支持llama3了
> > > ![image](https://private-user-images.githubusercontent.com/33342388/333269465-adb7e865-2c79-4754-9e9d-96514d2b1fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjk0NjUtYWRiN2U4NjUtMmM3OS00NzU0LTllOWQtOTY1MTRkMmIxZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjNiYWEwZjBmNzAyODRkN2Q4OTBlNGY4YmE0YzE2OTQ3MzUzMzgyODBjNmMyZDJiYmM5MjUwYjZhZTJkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwE1GX94vOnsdSjd1FUkyuOhrjpqFBOamMz8GbNAPXQ)
> > > 但是为什么我本地的插件没有看到llama3的选项呢？
> > > ![image](https://private-user-images.githubusercontent.com/33342388/333269330-82204e6e-aa9d-4ef3-a510-0b51364e0951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMwNjYsIm5iZiI6MTcxNjUxMjc2NiwicGF0aCI6Ii8zMzM0MjM4OC8zMzMyNjkzMzAtODIyMDRlNmUtYWE5ZC00ZWYzLWE1MTAtMGI1MTM2NGUwOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDUyMWE3NGE1NjQwYmMzNDljY2ViMjNjN2I5MDI3ZTgwYjkyNmI4ZDI2ZjAzMDA1M2IxNWE1NmJjMDhhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7qIpdtLUiEtYYS87yBj-AUcJuESlMwxWd4uznqLx4U)
> > > 请问是我的GPT PLUS没有更新吗？如果是没有更新的话，该在哪里查看插件的版本，以及如何更新插件呢？
> > 
> > 
> > 如果你是如下使用的
> > ```
> > git clone https://github.com/Kuingsmile/Word-GPT-Plus.git
> > yarn
> > yarn run serve
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 那git拉取下最新代码 然后重新运行后续yarn和yarn run serve命令就可以，后续考虑底部添加个版本号方便识别
> 
> 您好，我不是自己构建的服务，而是使用您这边使用Cloudflare Pages搭建的服务。看readme文件上面的描述，应该是自动更新的，但现在确实没有llama3，是不是您的releases和您搭建的服务没有匹配上（即releases更新了llama3，但是Cloudflare Pages没有更新）？

额 是的 cf page没自动部署 我刚才手动触发更新了哈 等会部署后就可以了

**Comment by jaycecd** [comment]
非常感谢您！
