### ISSUE TITLE
[Bug]: 404？405？

### ISSUE THREAD

**Issue by manesec** [Kuingsmile/word-GPT-Plus#5]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

开发者 你好，

在使用的时候我发现，使用API去请求，填写好了之后，点了保存，使用就会显示404，我有试过填写转发域名是word.msq.pub，就会405，看了一下文档没有解释关于“转发域名”，不知道要不要填，也不知道填得对不对（尴尬

我要如何解决该问题？

![image](https://user-images.githubusercontent.com/42072997/236576333-8f1869c7-a2e2-4e72-9d57-8bc3ce0d86c1.png)

![image](https://user-images.githubusercontent.com/42072997/236576416-9b16e1d5-2ca1-4fd6-8fa4-16fb4ce7c909.png)

**Comment by gao106** [comment]
我也这样，web-api也不行，不知道是不是魔法的原因

**Comment by Kuingsmile** [comment]
检查一下网络环境是否可用

**Comment by Kuingsmile** [comment]
转发域名是指通过这种服务转发的api接口对应地址https://github.com/noobnooc/noobnooc/discussions/9

**Comment by Kuingsmile** [comment]
由于切换model导致的bug，过会修复下

**Comment by Kuingsmile** [comment]
已修复官方接口的404 bug，web-api目前没有复现有问题 @manesec

**Comment by manesec** [comment]
转发域名一定要填写吗？ 不填写会显示 Error: Request failed with status code 400

**Comment by manesec** [comment]
![image](https://user-images.githubusercontent.com/42072997/236630959-c7f676f7-43bf-4d12-b781-db11709e817e.png)

**Comment by Kuingsmile** [comment]
不填转发域名的话需要开翻墙 不然国内访问会有问题

**Comment by Kuingsmile** [comment]
400的话可以试试把max token调大一点

**Comment by manesec** [comment]
感谢，已经解决了， max token在1000的时候可以正常工作了！
