### ISSUE TITLE
[Bug]: gpt-4-turbo token无法设置很高

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#53]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

<img width="454" alt="image" src="https://github.com/Kuingsmile/word-GPT-Plus/assets/13982749/213b679c-8632-4fc8-9f3f-0226b85490f7">
官方支持的token 数量为128000,而自己设置120000，却总提示上限为4000多，似乎不太对，不知哪里的错误

**Comment by Kuingsmile** [comment]
max_token是输出token数 最大4096
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/47bd103c-c4bf-4f4e-a3bb-bd07207308b7)

**Comment by fredericky123** [comment]
好吧，输入那么多，输出这么少
