### ISSUE TITLE
[Feature]: 模型又更新了，gpt-4o，请问能加个自定义模型的功能吗

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#54]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

不少软件有自定义输入的方式，这样以后模型更新自己手动输入模型名就好了，请问咱们能实现吗？感激！

**Comment by Kuingsmile** [comment]
已添加gpt-4o
