### ISSUE TITLE
[Bug]: yarn run serve 失败

### ISSUE THREAD

**Issue by xiaoToby** [Kuingsmile/word-GPT-Plus#55]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Linux

### Office 版本 | Office Version

others

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/40045458/5cb32f30-8e5c-4692-8890-efd7dbe96b7f)

**Comment by Kuingsmile** [comment]
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by xiaoToby** [comment]
是yarn run serve 错了嘛？@Kuingsmile

**Comment by xiaoToby** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/40045458/d3fab258-8859-4b68-ae24-ada6ef82dabc)
按这个步骤来的

**Comment by Kuingsmile** [comment]
你系统的问题 参考上面的链接重装试下

**Comment by xiaoToby** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/40045458/4bdf2c21-1084-452e-b3ae-ec48b561262d)
@Kuingsmile

**Comment by xiaoToby** [comment]
如果我想要用本地部署的模型，并提供了服务接口，怎么样让插件去使用这个模型？@Kuingsmile

**Comment by xiaoToby** [comment]
> 如果我想要用本地部署的模型，并提供了服务接口，怎么样让插件去使用这个模型？@Kuingsmile

@Kuingsmile
