### ISSUE TITLE
[Bug]: 错误: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

### ISSUE THREAD

**Issue by WenyanZhao** [Kuingsmile/word-GPT-Plus#56]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 问题重现 | Bug reproduce

word加载插件后是个空白页什么都不显示，点击调试报错如下：错误: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

**Comment by Kuingsmile** [comment]
参考 https://github.com/Kuingsmile/word-GPT-Plus/issues/3

office 2016 retail版本需要额外安装webview2，如果还是不行更换office 365版本即可
