### ISSUE TITLE
[Bug]: ollama endpoint怎么填，怎么调用自己的olllama服务

### ISSUE THREAD

**Issue by WenyanZhao** [Kuingsmile/word-GPT-Plus#57]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

![Dingtalk_20240529161135](https://github.com/Kuingsmile/word-GPT-Plus/assets/43986888/a652fdfc-41d8-4774-b637-12706613099c)

**Comment by Kuingsmile** [comment]
https://github.com/ollama/ollama 参考ollama文档  一般是你部署地址的11434端口

**Comment by WenyanZhao** [comment]
> https://github.com/ollama/ollama 参考ollama文档 一般是你部署地址的11434端口

endpoint我填写的就是自己的ollama服务 例如：http://IP:11434 但是不行呀，根本过去不去，调用报错信息如下
![Dingtalk_20240530094156](https://github.com/Kuingsmile/word-GPT-Plus/assets/43986888/a5033283-d066-49ef-b964-cd48889de9c7)

**Comment by Kuingsmile** [comment]
![Screenshot_2024_0530_135922.png](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/6aa0c76d-a9a3-469d-836e-cdc137faaf91)

你这个地址为什么还有个3000端口

**Comment by WenyanZhao** [comment]
> ![Screenshot_2024_0530_135922.png](https://private-user-images.githubusercontent.com/96409857/335058188-6aa0c76d-a9a3-469d-836e-cdc137faaf91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjM1ODAsIm5iZiI6MTcxNzEyMzI4MCwicGF0aCI6Ii85NjQwOTg1Ny8zMzUwNTgxODgtNmFhMGM3NmQtYTlhMy00NjlkLTgzNmUtY2RjMTM3ZmFhZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMmUzMjllNmNiMDZhMGVlMjE5MDU5N2FlNDAzZTIyNjhkOTI5NWQ2NTczMTI0YjQyNGMxY2E4OWFlZjM3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E-Lm6VVU1QpVoqAMckgxKyX5lArxx12-J8-t13Q9Dyo)
> 
> 你这个地址为什么还有个3000端口

10.56.0.210:3000是自己部署的前端服务，10.56.0.49:11413是ollama服务，所以很奇怪使用的时候居然是这样的地址

**Comment by Kuingsmile** [comment]
endpoint怎么填的

**Comment by WenyanZhao** [comment]
> endpoint怎么填的

10.56.0.49:11413以及http://10.56.0.49:11413 都试过

**Comment by WenyanZhao** [comment]
> endpoint怎么填的

填http://10.56.0.49:11413 这个可以但是报NetworkError
