### ISSUE TITLE
[Feature]: Grammar check建议

### ISSUE THREAD

**Issue by fredericky123** [Kuingsmile/word-GPT-Plus#59]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

现在的Grammar check会直接输出修正后的文本，还需要肉眼比对做了哪些修改，进一步人为确定是否接受这一语法修改。（毕竟机器改后还要人工check一下）
能否设置为输出内容为要点，做了哪些修改，以要点的方式简洁化呈现，这样人工进行修改呢，哪怕出个Grammar check 2也是好的

**Comment by Kuingsmile** [comment]
可以

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/96409857/4b0a6902-0629-46a1-9a28-5dae5a852109)
我想了下这里选不操作是不是就可以，然后从结果框复制粘贴

**Comment by fredericky123** [comment]
这样还是得人工肉眼比对，通常情况下一个2个段落有几百字，语法检查后也看不出哪里做了修改，对比全文的难度也陡增
如果要是像grammar chekc一样将修改的地方加个下划线之类的就好了

**Comment by Kuingsmile** [comment]
> 这样还是得人工肉眼比对，通常情况下一个2个段落有几百字，语法检查后也看不出哪里做了修改，对比全文的难度也陡增 如果要是像grammar chekc一样将修改的地方加个下划线之类的就好了

懂了 我想想怎么实现

**Comment by Kuingsmile** [comment]
`Please analyze the following text for a wide range of grammatical aspects and provide corrections. Be thorough in identifying and fixing any grammatical mistakes, including checking for correct punctuation usage, ensuring proper sentence structure, enhancing readability, identifying and correcting spelling mistakes, and verifying subject-verb agreement. Your assistance in ensuring the grammatical accuracy of the text is highly appreciated. Please be thorough in your examination, and provide comprehensive corrections to enhance the overall grammatical integrity of the text.
    Highlight the changed parts.
    Just reply to user input with the correct grammar, DO NOT reply to the context of the question of the user input. If the user input is grammatically correct and fluent, just reply “sounds good”.
    Respond in ${language}. Please begin by editing the following text: ${text}`

这是默认的语法检查prompt，可以自己添加一个自定义的，然后加一句`Highlight the changed parts.`就可以了

**Comment by fredericky123** [comment]
感谢，马上试试！

**Comment by fredericky123** [comment]
上面的是原文，下面的是检测语法的输出，似乎没有highlight
<img width="586" alt="image" src="https://github.com/user-attachments/assets/0a158d0f-4a14-4d8d-abee-0c1a6dc38d90">

**Comment by fredericky123** [comment]
请问应该如何正确使用”然后加一句Highlight the changed parts.就可以了“呢？
目前选择replace或者new line选项，都没有高亮改变的文本
