### ISSUE TITLE
[Feature]:  Add Stable Horde, discord.rocks and open router support

### ISSUE THREAD

**Issue by tukangcode** [Kuingsmile/word-GPT-Plus#62]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2019 retail

### 功能请求 | Feature request

can add support for 
- [aihorde](https://stablehorde.net/)
- https://api.discord.rocks/
- [OpenRouter](https://openrouter.ai/)
thanks

**Comment by Kuingsmile** [comment]
will try

**Comment by tukangcode** [comment]
thanks

**Comment by Kuingsmile** [comment]
It seems https://api.discord.rocks/ and [OpenRouter](https://openrouter.ai/) is compatible with openai api, just change the base url and model name.

**Comment by tukangcode** [comment]
thanks but it seem it not possible to use stable horde for now since they not provide they api documentaion
