### ISSUE TITLE
[Bug]: 设置转发网址无效

### ISSUE THREAD

**Issue by flangk** [Kuingsmile/word-GPT-Plus#63]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

设置转发网址没有效果

**Comment by fredericky123** [comment]
设置token也无法保存

**Comment by Ford666** [comment]
我是设置API key不能保存，每次都自动清除了，请问有人遇到过吗？
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/35663131/ba5f9901-da6b-4607-b9e4-5bb3dca8369d)

**Comment by Kuingsmile** [comment]
我查一下  可能是上次改架构改出问题了

**Comment by Ford666** [comment]
@Kuingsmile 感谢博主！已经可以正常使用
