### ISSUE TITLE
[Feature]:  Add Groq Ai support

### ISSUE THREAD

**Issue by tukangcode** [Kuingsmile/word-GPT-Plus#64]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2019 retail

### 功能请求 | Feature request

Please add support for grog ai to

**Comment by Kuingsmile** [comment]
https://groq.com/ this one?

**Comment by tukangcode** [comment]
yes, it api is free currently and limit are generous

**Comment by Kuingsmile** [comment]
where is the api doc?
