### ISSUE TITLE
[Bug]: yarn run serve出现错误

### ISSUE THREAD

**Issue by Cyan2077** [Kuingsmile/word-GPT-Plus#66]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 问题重现 | Bug reproduce

![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/151855984/a8c4542c-e90f-4e5c-8b16-1ecc01fd41e0)
这个本地部署，部署完最后一步出现error
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/151855984/a5c0423d-4a12-4096-b1ab-9a6b1837396e)
不太理解该error产生的原因，出现很多条类似于下面的东西
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/151855984/75eb9cbd-c2ec-4650-9ec6-07a2ca93da8c)

**Comment by Kuingsmile** [comment]
`git config--global core.autocrlf false` 然后删掉clone的代码之后重新clone

**Comment by Cyan2077** [comment]
编译成功了，但是好像又有新的问题
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/151855984/9e4491cb-403b-4ec8-a197-15d339844181)
好像在word中侧边栏还是空白的

word 2016版
![image](https://github.com/Kuingsmile/word-GPT-Plus/assets/151855984/be67e3af-9dc9-4b23-8019-aad5f63031d2)

**Comment by Kuingsmile** [comment]
2016版本只支持零售版 而且需要安装webview2 建议使用365版本
