### ISSUE TITLE
[Feature]: 求大佬开发Excel的插件

### ISSUE THREAD

**Issue by msn1983aa** [Kuingsmile/word-GPT-Plus#67]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

请求大佬百忙之中开发一个针对Excel的插件，Excel使用场景和用途也很广泛，谢谢了

**Comment by Kuingsmile** [comment]
暂不考虑
