### ISSUE TITLE
[Feature]: 非常好用！请求作者增加增加像国内的中转接口

### ISSUE THREAD

**Issue by ananzibian** [Kuingsmile/word-GPT-Plus#68]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 功能请求 | Feature request

非常好用！请求作者增加增加像国内的中转接口例如 https://api.chatanywhere.com.cn，https://api.openai.one以及https://oa.api2d.net等

**Comment by Kuingsmile** [comment]
使用官方接口的时候设置转发域名应该就可以

**Comment by ananzibian** [comment]
好的 刚试了所有中专api 有些国内的不能用 有些可以 谢谢作者回复。另外，作者考虑以后加excel gpt吗

**Comment by Kuingsmile** [comment]
> 好的 刚试了所有中专api 有些国内的不能用 有些可以 谢谢作者回复。另外，作者考虑以后加excel gpt吗

暂时不考虑

**Comment by ananzibian** [comment]
好的 谢谢作者！

**Comment by s23ir45** [comment]
请问作者使用官方接口的时候怎么设置转发域名啊？
