### ISSUE TITLE
mac microsoft 365 教程可否出一个？谢谢

### ISSUE THREAD

**Issue by ocean-zhc** [Kuingsmile/word-GPT-Plus#7]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Mac

### Office 版本 | Office Version

microsoft 365

### 功能请求 | Feature request

mac Microsoft365 教程可否出一份？谢谢

**Comment by Kuingsmile** [comment]
[https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac
](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac
)
请参考这个，微软的官方教程

**Comment by ocean-zhc** [comment]
> [https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac ](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac)
> 请参考这个，微软的官方教程

谢谢，可以了。
