### ISSUE TITLE
C:\Users\Administrator\Documents\WordGPT>yarn run serve 错误: 找不到或无法加载主类 run

### ISSUE THREAD

**Issue by bozaichat** [Kuingsmile/word-GPT-Plus#9]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2016 retail

### 问题重现 | Bug reproduce

C:\Users\Administrator\Documents\WordGPT>yarn run serve
错误: 找不到或无法加载主类 run

**Comment by Kuingsmile** [comment]
全局安装yarn了么 `npm install --global yarn`
